# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
    default:
        - parallel:
              - step:
                    script:
                        - docker
                    services:
                        - docker
                    caches:
                        - docker
              - step:
                    name: Test
                    script:
                        - cd main
                        - composer install
                        -  ./vendor/bin/phpunit tests
                    caches:
                        - composer
              - step:
                    name: Lint
                    script:
                        - cd main
                        - composer install
                        - .bin/phpcs --standard=PSR2 src -n
                        - .bin/php-cs-fixer fix . --config=sf23 --dry-run -vv
                    caches:
                        - composer
definitions:
    services:
        docker:
            memory: 2048