# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
    default:
        - parallel:
              - step:
                    script:
                        - docker
                    services:
                        - docker
                    caches:
                        - docker
              - step:
                    name: Test
                    script:
                        - cd main
                        - composer install
                        -  ./vendor/bin/phpunit test
                    caches:
                        - composer
              - step:
                    name: Lint
                    script:
                        - composer install
                        - ./vendor/bin/phplint . --exclude=vendor
                    caches:
                        - composer
definitions:
    services:
        docker:
            memory: 2048