version: '2'

services:
    database:
        build:
            context: docker/db
        image: db-mf
        networks:
            - sym4
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_USER=test
            - MYSQL_PASSWORD=1234
            - MYSQL_ROOT_PASSWORD=docker
        container_name: sym4Database
        ports:
            - "3303:3306"

    php-fpm:
        build:
            context: docker/php
        image: php-fpm-mf
        networks:
            - sym4
        depends_on:
            - database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?10.5.8-MariaDB-1:10.5.8+maria~focal
        volumes:
            - ./app:/app
            - ./logs:/var/log/nginx
            - ./logs/xdebug:/var/log/xdebug
            - ./docker/php/:/usr/local/etc/php
            - ./docker/php/ini/custom.ini:/usr/local/etc/php/conf.d/
        container_name: sym4Web
        ports:
            - "9000:9000"
        #command: [nginx-debug, '-g', 'daemon off;']
    nginx:
        build:
            context: docker/nginx
        image: nginx-mf
        networks:
            - sym4
        volumes:
            - ./app:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log/nginx
            - ./docker/nginx/:/usr/local/etc/php
        depends_on:
            - php-fpm
        ports:
            - "8055:80"
        container_name: sym4Server
        command: [nginx-debug, '-g', 'daemon off;']

#    redis:
#        build:
##            context: docker/redis
#        image: redis-mf
#        networks:
#             - sym4
#        container_name: sym4Redis
#        privileged: true
#        command: sh -c "./init.sh"
#        volumes:
#            - ./redisData:/data
#        ports:
#            - "6379:6379"
networks:
    sym4:
        ipam:
            driver: default
            config:
                -   subnet: 172.99.0.0/16
                    gateway: 172.99.0.1

