version: '2'

services:
    database:
        build:
            context: docker/db
        image: db-mf
        networks:
            - snare
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        container_name: database
        ports:
            - "3303:3306"

    php-fpm:
        build:
            context: docker/php
        image: php-fpm-mf
        networks:
            - snare
        depends_on:
            - database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?10.5.8-MariaDB-1:10.5.8+maria~focal
        volumes:
            - ./main:/main
            - ./logs:/var/log/nginx
            - ./logs/xdebug:/var/log/xdebug
            - ./docker/php/:/usr/local/etc/php
          #  - ./docker/php/ini/custom.ini:/usr/local/etc/php/conf.d/
        container_name: web
        ports:
            - "9000:9000"
        #command: [nginx-debug, '-g', 'daemon off;']
    nginx:
        build:
            context: docker/nginx
        image: nginx-mf
        networks:
            - snare
        volumes:
            - ./main:/main
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log/nginx
            - ./docker/nginx/:/usr/local/etc/php
        depends_on:
            - php-fpm
        ports:
            - "8055:80"
        container_name: server
        command: [nginx-debug, '-g', 'daemon off;']

networks:
    snare:
        ipam:
            driver: default
            config:
                -   subnet: 172.99.0.0/16
                    gateway: 172.99.0.1

